name: Build Homebrew

on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d3fau4/nx-dev:main  # or change 'latest' to 'v4.2.0' if you want compile with the release of libnx
    steps:
    - uses: actions/checkout@v3
    - name: Update repo.
      run: |
        git submodule update --init --recursive
        
    - name: Build app
      run: |
        make -j$(nproc) dist
        
    - uses: actions/upload-artifact@master
      with:
        name: Package
        path: out/